server:
  port: 9411
spring:
  application:
    name: zipkin-server
management:

  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true
