eureka:
  numberRegistrySyncRetries: 1
  instance:
    preferIpAddress: false
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
server:
  port: 8000
spring:
  application:
    name: eureka-server